name: Build and Test Client Application
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install modules
        run: npm i

      - name: Run tests
        run: npm run test
